name: Build & deploy app to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17

    - name: Unit Tests
      run: mvn -B test

    - name: Build the app
      run: |
        mvn clean
        mvn -B package

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME}}/demo:${{ github.sha }}

    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push to Docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME}}/demo:${{ github.sha }}

    - name: Deploy to EC2
      run: |
        export SSH_KEY=key.pem
        cat <<< "${{ secrets.EC2_SSH_KEY }}" > $SSH_KEY
        chmod 400 $SSH_KEY
        ssh -i $SSH_KEY ec2-user@${{ secrets.EC2_PUBLIC_DOMAIN}} -o StrictHostKeyChecking=no
        mkdir test